"""initial platform schema

Revision ID: 78215b6f43e5
Revises: 
Create Date: 2026-08-14 19:26:17.627501
"""

import sqlalchemy as sa

from alembic import op

revision = '78215b6f43e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_manifests',
    sa.Column('manifest_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('accepted_inputs', sa.JSON(), nullable=False),
    sa.Column('produced_outputs', sa.JSON(), nullable=False),
    sa.Column('requested_capabilities', sa.JSON(), nullable=False),
    sa.Column('allowed_tools', sa.JSON(), nullable=False),
    sa.Column('forbidden_tools', sa.JSON(), nullable=False),
    sa.Column('authority_ceiling', sa.String(length=32), nullable=False),
    sa.Column('evidence_consumed', sa.JSON(), nullable=False),
    sa.Column('evidence_produced', sa.JSON(), nullable=False),
    sa.Column('escalation_rules', sa.JSON(), nullable=False),
    sa.Column('refusal_rules', sa.JSON(), nullable=False),
    sa.Column('model_policy', sa.Text(), nullable=False),
    sa.Column('timeout_policy', sa.Text(), nullable=False),
    sa.Column('retry_policy', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('manifest_id'),
    sa.UniqueConstraint('agent_id', 'version', name='uq_agent_manifest_version')
    )
    op.create_index(op.f('ix_agent_manifests_agent_id'), 'agent_manifests', ['agent_id'], unique=True)
    op.create_table('capability_manifests',
    sa.Column('capability_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('risk_class', sa.String(length=16), nullable=False),
    sa.Column('accepted_inputs', sa.JSON(), nullable=False),
    sa.Column('produced_outputs', sa.JSON(), nullable=False),
    sa.Column('required_authority', sa.String(length=32), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('sandbox_profile', sa.String(length=64), nullable=False),
    sa.Column('sandbox_requirement', sa.String(length=16), nullable=False),
    sa.Column('network_policy', sa.String(length=32), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('resource_limits', sa.JSON(), nullable=False),
    sa.Column('tool_identity', sa.String(length=128), nullable=False),
    sa.Column('tool_version', sa.String(length=32), nullable=False),
    sa.Column('evidence_type', sa.String(length=64), nullable=False),
    sa.Column('command_allowlist', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('capability_id', 'version'),
    sa.UniqueConstraint('capability_id')
    )
    op.create_table('clients',
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_table('principals',
    sa.Column('principal_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('manifest_ref', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('principal_id')
    )
    op.create_table('targets',
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('target_id')
    )
    op.create_table('workflow_side_effects',
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('effect', sa.JSON(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('idempotency_key')
    )
    op.create_table('baselines',
    sa.Column('baseline_id', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['targets.target_id'], ),
    sa.PrimaryKeyConstraint('baseline_id')
    )
    op.create_table('engagements',
    sa.Column('engagement_id', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('requester_principal_id', sa.String(length=64), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('pass_type', sa.String(length=32), nullable=False),
    sa.Column('authority_level', sa.String(length=32), nullable=False),
    sa.Column('constraints', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('status_history', sa.JSON(), nullable=False),
    sa.Column('refusal_reason', sa.Text(), nullable=True),
    sa.Column('suspended_from', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.ForeignKeyConstraint(['requester_principal_id'], ['principals.principal_id'], ),
    sa.PrimaryKeyConstraint('engagement_id')
    )
    op.create_index(op.f('ix_engagements_client_id'), 'engagements', ['client_id'], unique=False)
    op.create_index(op.f('ix_engagements_status'), 'engagements', ['status'], unique=False)
    op.create_table('adjudications',
    sa.Column('adjudication_id', sa.String(length=64), nullable=False),
    sa.Column('engagement_id', sa.String(length=64), nullable=False),
    sa.Column('claim_ids', sa.JSON(), nullable=False),
    sa.Column('supporting_evidence_ids', sa.JSON(), nullable=False),
    sa.Column('contradicting_evidence_ids', sa.JSON(), nullable=False),
    sa.Column('verdict', sa.String(length=32), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('specialist_identity', sa.String(length=128), nullable=False),
    sa.Column('tool_confidence', sa.String(length=16), nullable=True),
    sa.Column('scope_note', sa.Text(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.engagement_id'], ),
    sa.PrimaryKeyConstraint('adjudication_id')
    )
    op.create_index(op.f('ix_adjudications_engagement_id'), 'adjudications', ['engagement_id'], unique=False)
    op.create_table('agent_runs',
    sa.Column('agent_run_id', sa.String(length=64), nullable=False),
    sa.Column('engagement_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('agent_version', sa.String(length=32), nullable=False),
    sa.Column('model_identity', sa.String(length=128), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('principal_id', sa.String(length=64), nullable=False),
    sa.Column('authority_refs', sa.JSON(), nullable=False),
    sa.Column('input_refs', sa.JSON(), nullable=False),
    sa.Column('tool_invocation_ids', sa.JSON(), nullable=False),
    sa.Column('output_claim_ids', sa.JSON(), nullable=False),
    sa.Column('evidence_ids', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_manifests.agent_id'], ),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.engagement_id'], ),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.principal_id'], ),
    sa.PrimaryKeyConstraint('agent_run_id')
    )
    op.create_index(op.f('ix_agent_runs_engagement_id'), 'agent_runs', ['engagement_id'], unique=False)
    op.create_table('approvals',
    sa.Column('approval_id', sa.String(length=64), nullable=False),
    sa.Column('engagement_id', sa.String(length=64), nullable=False),
    sa.Column('requested_by_principal_id', sa.String(length=64), nullable=False),
    sa.Column('decided_by_principal_id', sa.String(length=64), nullable=True),
    sa.Column('request_ref', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('capability_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['decided_by_principal_id'], ['principals.principal_id'], ),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.engagement_id'], ),
    sa.ForeignKeyConstraint(['requested_by_principal_id'], ['principals.principal_id'], ),
    sa.PrimaryKeyConstraint('approval_id'),
    sa.UniqueConstraint('engagement_id', 'request_ref', name='uq_approval_request')
    )
    op.create_index(op.f('ix_approvals_engagement_id'), 'approvals', ['engagement_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('audit_event_id', sa.String(length=64), nullable=False),
    sa.Column('engagement_id', sa.String(length=64), nullable=True),
    sa.Column('principal_id', sa.String(length=64), nullable=True),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('previous_event_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.engagement_id'], ),
    sa.ForeignKeyConstraint(['previous_event_id'], ['audit_events.audit_event_id'], ),
    sa.PrimaryKeyConstraint('audit_event_id')
    )
    op.create_index(op.f('ix_audit_events_engagement_id'), 'audit_events', ['engagement_id'], unique=False)
    op.create_index('ix_audit_events_engagement_occurred', 'audit_events', ['engagement_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_events_kind'), 'audit_events', ['kind'], unique=False)
    op.create_index(op.f('ix_audit_events_occurred_at'), 'audit_events', ['occurred_at'], unique=False)
    op.create_table('authority_grants',
    sa.Column('grant_id', sa.String(length=64), nullable=False),
    sa.Column('engagement_id', sa.String(length=64), nullable=False),
    sa.Column('principal_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('capability_id', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('not_before', sa.DateTime(timezone=True), nullable=False),
    sa.Column('not_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.engagement_id'], ),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.principal_id'], ),
    sa.PrimaryKeyConstraint('grant_id')
    )
    op.create_index(op.f('ix_authority_grants_engagement_id'), 'authority_grants', ['engagement_id'], unique=False)
    op.create_index(op.f('ix_authority_grants_principal_id'), 'authority_grants', ['principal_id'], unique=False)
    op.create_table('drift_events',
    sa.Column('drift_event_id', sa.String(length=64), nullable=False),
    sa.Column('baseline_id', sa.String(length=64), nullable=False),
    sa.Column('engagement_id', sa.String(length=64), nullable=True),
    sa.Column('drift_kind', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['baseline_id'], ['baselines.baseline_id'], ),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.engagement_id'], ),
    sa.PrimaryKeyConstraint('drift_event_id')
    )
    op.create_index(op.f('ix_drift_events_baseline_id'), 'drift_events', ['baseline_id'], unique=False)
    op.create_table('engagement_targets',
    sa.Column('engagement_target_id', sa.String(length=64), nullable=False),
    sa.Column('engagement_id', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('in_scope', sa.Boolean(), nullable=False),
    sa.Column('scope_note', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.engagement_id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['targets.target_id'], ),
    sa.PrimaryKeyConstraint('engagement_target_id'),
    sa.UniqueConstraint('engagement_id', 'target_id', name='uq_engagement_target')
    )
    op.create_index(op.f('ix_engagement_targets_engagement_id'), 'engagement_targets', ['engagement_id'], unique=False)
    op.create_index(op.f('ix_engagement_targets_target_id'), 'engagement_targets', ['target_id'], unique=False)
    op.create_table('observations',
    sa.Column('observation_id', sa.String(length=64), nullable=False),
    sa.Column('engagement_id', sa.String(length=64), nullable=False),
    sa.Column('evidence_ids', sa.JSON(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('recorded_by_agent_id', sa.String(length=64), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.engagement_id'], ),
    sa.PrimaryKeyConstraint('observation_id')
    )
    op.create_index(op.f('ix_observations_engagement_id'), 'observations', ['engagement_id'], unique=False)
    op.create_table('refusals',
    sa.Column('refusal_id', sa.String(length=64), nullable=False),
    sa.Column('engagement_id', sa.String(length=64), nullable=True),
    sa.Column('requested_by_principal_id', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.engagement_id'], ),
    sa.PrimaryKeyConstraint('refusal_id')
    )
    op.create_table('reports',
    sa.Column('report_id', sa.String(length=64), nullable=False),
    sa.Column('engagement_id', sa.String(length=64), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('findings_count', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.String(length=16), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('no_secrets_asserted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.engagement_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_index(op.f('ix_reports_engagement_id'), 'reports', ['engagement_id'], unique=False)
    op.create_table('workflow_runs',
    sa.Column('workflow_run_id', sa.String(length=64), nullable=False),
    sa.Column('engagement_id', sa.String(length=64), nullable=False),
    sa.Column('started_by_principal_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_phase', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.engagement_id'], ),
    sa.ForeignKeyConstraint(['started_by_principal_id'], ['principals.principal_id'], ),
    sa.PrimaryKeyConstraint('workflow_run_id')
    )
    op.create_index(op.f('ix_workflow_runs_engagement_id'), 'workflow_runs', ['engagement_id'], unique=False)
    op.create_table('claims',
    sa.Column('claim_id', sa.String(length=64), nullable=False),
    sa.Column('engagement_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('agent_run_id', sa.String(length=64), nullable=False),
    sa.Column('observation_ids', sa.JSON(), nullable=False),
    sa.Column('evidence_ids', sa.JSON(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('uncertainty', sa.Text(), nullable=False),
    sa.Column('supporting_note', sa.Text(), nullable=False),
    sa.Column('made_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.agent_run_id'], ),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.engagement_id'], ),
    sa.PrimaryKeyConstraint('claim_id')
    )
    op.create_index(op.f('ix_claims_engagement_id'), 'claims', ['engagement_id'], unique=False)
    op.create_table('findings',
    sa.Column('finding_id', sa.String(length=64), nullable=False),
    sa.Column('engagement_id', sa.String(length=64), nullable=False),
    sa.Column('originating_adjudication_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('impact', sa.Text(), nullable=False),
    sa.Column('remediation_guidance', sa.Text(), nullable=False),
    sa.Column('verification_step', sa.Text(), nullable=False),
    sa.Column('supporting_evidence_ids', sa.JSON(), nullable=False),
    sa.Column('contradicting_evidence_ids', sa.JSON(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('closed_by_principal_id', sa.String(length=64), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['closed_by_principal_id'], ['principals.principal_id'], ),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.engagement_id'], ),
    sa.ForeignKeyConstraint(['originating_adjudication_id'], ['adjudications.adjudication_id'], ),
    sa.PrimaryKeyConstraint('finding_id')
    )
    op.create_index(op.f('ix_findings_engagement_id'), 'findings', ['engagement_id'], unique=False)
    op.create_table('tool_invocations',
    sa.Column('tool_invocation_id', sa.String(length=64), nullable=False),
    sa.Column('engagement_id', sa.String(length=64), nullable=False),
    sa.Column('workflow_run_id', sa.String(length=64), nullable=False),
    sa.Column('capability_id', sa.String(length=64), nullable=False),
    sa.Column('agent_run_id', sa.String(length=64), nullable=True),
    sa.Column('requested_by_principal_id', sa.String(length=64), nullable=False),
    sa.Column('policy_decision', sa.String(length=32), nullable=False),
    sa.Column('approval_id', sa.String(length=64), nullable=True),
    sa.Column('sandbox_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_evidence_ids', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.agent_run_id'], ),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.approval_id'], ),
    sa.ForeignKeyConstraint(['capability_id'], ['capability_manifests.capability_id'], ),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.engagement_id'], ),
    sa.ForeignKeyConstraint(['requested_by_principal_id'], ['principals.principal_id'], ),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.workflow_run_id'], ),
    sa.PrimaryKeyConstraint('tool_invocation_id')
    )
    op.create_index(op.f('ix_tool_invocations_engagement_id'), 'tool_invocations', ['engagement_id'], unique=False)
    op.create_index(op.f('ix_tool_invocations_status'), 'tool_invocations', ['status'], unique=False)
    op.create_table('evidence_metadata',
    sa.Column('evidence_id', sa.String(length=64), nullable=False),
    sa.Column('engagement_id', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('collector', sa.String(length=128), nullable=False),
    sa.Column('tool_version', sa.String(length=32), nullable=False),
    sa.Column('capability_id', sa.String(length=64), nullable=False),
    sa.Column('invocation_id', sa.String(length=64), nullable=False),
    sa.Column('sandbox_id', sa.String(length=64), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_ref', sa.String(length=512), nullable=False),
    sa.Column('sanitization_state', sa.String(length=32), nullable=False),
    sa.Column('source_identity', sa.String(length=128), nullable=False),
    sa.Column('agent_run_id', sa.String(length=64), nullable=True),
    sa.Column('secret_observations', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.agent_run_id'], ),
    sa.ForeignKeyConstraint(['capability_id'], ['capability_manifests.capability_id'], ),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.engagement_id'], ),
    sa.ForeignKeyConstraint(['invocation_id'], ['tool_invocations.tool_invocation_id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['targets.target_id'], ),
    sa.PrimaryKeyConstraint('evidence_id'),
    sa.UniqueConstraint('sha256', 'engagement_id', name='uq_evidence_sha256_engagement')
    )
    op.create_index(op.f('ix_evidence_metadata_engagement_id'), 'evidence_metadata', ['engagement_id'], unique=False)
    op.create_index(op.f('ix_evidence_metadata_sha256'), 'evidence_metadata', ['sha256'], unique=False)
    op.create_table('remediations',
    sa.Column('remediation_id', sa.String(length=64), nullable=False),
    sa.Column('engagement_id', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('finding_id', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('applied_by_principal_id', sa.String(length=64), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rollback_note', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.engagement_id'], ),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.finding_id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['targets.target_id'], ),
    sa.PrimaryKeyConstraint('remediation_id')
    )
    op.create_index(op.f('ix_remediations_engagement_id'), 'remediations', ['engagement_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_remediations_engagement_id'), table_name='remediations')
    op.drop_table('remediations')
    op.drop_index(op.f('ix_evidence_metadata_sha256'), table_name='evidence_metadata')
    op.drop_index(op.f('ix_evidence_metadata_engagement_id'), table_name='evidence_metadata')
    op.drop_table('evidence_metadata')
    op.drop_index(op.f('ix_tool_invocations_status'), table_name='tool_invocations')
    op.drop_index(op.f('ix_tool_invocations_engagement_id'), table_name='tool_invocations')
    op.drop_table('tool_invocations')
    op.drop_index(op.f('ix_findings_engagement_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_claims_engagement_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_workflow_runs_engagement_id'), table_name='workflow_runs')
    op.drop_table('workflow_runs')
    op.drop_index(op.f('ix_reports_engagement_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_table('refusals')
    op.drop_index(op.f('ix_observations_engagement_id'), table_name='observations')
    op.drop_table('observations')
    op.drop_index(op.f('ix_engagement_targets_target_id'), table_name='engagement_targets')
    op.drop_index(op.f('ix_engagement_targets_engagement_id'), table_name='engagement_targets')
    op.drop_table('engagement_targets')
    op.drop_index(op.f('ix_drift_events_baseline_id'), table_name='drift_events')
    op.drop_table('drift_events')
    op.drop_index(op.f('ix_authority_grants_principal_id'), table_name='authority_grants')
    op.drop_index(op.f('ix_authority_grants_engagement_id'), table_name='authority_grants')
    op.drop_table('authority_grants')
    op.drop_index(op.f('ix_audit_events_occurred_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_kind'), table_name='audit_events')
    op.drop_index('ix_audit_events_engagement_occurred', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_engagement_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_approvals_engagement_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_agent_runs_engagement_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_adjudications_engagement_id'), table_name='adjudications')
    op.drop_table('adjudications')
    op.drop_index(op.f('ix_engagements_status'), table_name='engagements')
    op.drop_index(op.f('ix_engagements_client_id'), table_name='engagements')
    op.drop_table('engagements')
    op.drop_table('baselines')
    op.drop_table('workflow_side_effects')
    op.drop_table('targets')
    op.drop_table('principals')
    op.drop_table('clients')
    op.drop_table('capability_manifests')
    op.drop_index(op.f('ix_agent_manifests_agent_id'), table_name='agent_manifests')
    op.drop_table('agent_manifests')
    # ### end Alembic commands ###
