import type { PreviewData } from "./types";

const origin = "SYNTHETIC" as const;

export const previewData: PreviewData = {
  mode: "PREVIEW",
  originLabel: "SYNTHETIC / NON-PERSONAL / NON-CLIENT / QUALIFICATION_ONLY",
  engagements: [
    {
      engagementId: "ENG-2026-015",
      clientId: "CLI-VPP",
      clientName: "Synthetic agent client",
      targetIds: ["TGT-VPP-SNAPSHOT"],
      targetLabel: "immutable repository snapshot",
      snapshotLabel: "digest-bound · qualification artifact",
      scope: "Immutable snapshot inspection and bounded cross-layer review.",
      passType: "posture assessment",
      authorityLevel: "inspection-only",
      constraints: ["no client writes", "no active testing", "no credential attacks"],
      status: "closed",
      updatedAt: "2026-08-15T18:40:00Z",
      findingCount: 1,
      origin,
    },
    {
      engagementId: "ENG-2026-022",
      clientId: "CLI-AGENT",
      clientName: "Agent Systems Lab",
      targetIds: ["TGT-AGENT-SNAPSHOT"],
      targetLabel: "agent repository snapshot",
      snapshotLabel: "immutable snapshot · pending review",
      scope: "Agent identity, authority, tool, and memory boundary inspection.",
      passType: "posture assessment",
      authorityLevel: "inspection-only",
      constraints: ["no client writes", "no active testing"],
      status: "reporting",
      updatedAt: "2026-08-16T10:20:00Z",
      findingCount: 0,
      origin,
    },
  ],
  findings: [
    {
      findingId: "FND-PREV-015",
      engagementId: "ENG-2026-015",
      severity: "Low",
      summary: "A review capability reported unavailable advisory data under its network-none policy.",
      impact: "The affected capability is not qualified for this snapshot; no unsupported conclusion is issued.",
      status: "open",
      confidence: "high",
      adjudication: "SUPPORTED",
      supportingEvidenceIds: ["E-1181"],
      contradictingEvidenceIds: [],
      verificationStep: "Re-run with an approved offline advisory database artifact.",
      remediationGuidance: "Record the capability as not qualified until its advisory source is available.",
      origin,
    },
  ],
  evidence: [
    {
      evidenceId: "E-1181",
      engagementId: "ENG-2026-015",
      targetId: "TGT-VPP-SNAPSHOT",
      targetSnapshot: "Synthetic agent client · immutable snapshot",
      collector: "Security Review Specialist V1",
      toolVersion: "deterministic-fake-v1",
      capabilityId: "CAP-ADVISORY-READ",
      invocationId: "INV-015-18",
      collectedAt: "2026-08-15T17:44:00Z",
      contentType: "application/json",
      byteSize: 1210,
      sha256: "a1de…721c",
      storageRef: "metadata://evidence/E-1181",
      sanitizationState: "SANITIZED",
      usedBy: ["FND-PREV-015", "RPT-015"],
      origin,
    },
  ],
  runs: [
    {
      agentRunId: "AR-015-COORD-01",
      engagementId: "ENG-2026-015",
      agentId: "agent.security-review-v1",
      agentRole: "Security Review Specialist",
      agentVersion: "1.0.0",
      modelIdentity: "deterministic-fake-v1",
      promptVersion: "security-review-v1",
      status: "completed",
      startedAt: "2026-08-15T17:40:00Z",
      finishedAt: "2026-08-15T17:45:00Z",
      authorityRefs: ["inspection-only"],
      capabilityIds: ["CAP-ADVISORY-READ"],
      toolInvocationIds: ["INV-015-18"],
      evidenceIds: ["E-1181"],
      outputClaimIds: ["CL-015"],
      origin,
    },
  ],
  capabilities: [
    {
      capabilityId: "CAP-ADVISORY-READ",
      version: "0.1.0",
      description: "Read a permitted advisory artifact under the engagement snapshot boundary.",
      riskClass: "medium",
      requiredAuthority: "inspect",
      requiresApproval: true,
      sandboxProfile: "readonly-advisory",
      networkPolicy: "none",
      timeoutSeconds: 90,
      resourceLimits: { cpu: "1", memory: "512MiB", pids: "64" },
      toolIdentity: "advisory-reader",
      toolVersion: "0.1.0",
      evidenceType: "advisory-metadata",
      origin,
    },
  ],
  securityServices: [
    { serviceId: "APPSEC", name: "Application Security", version: "0.1.0", qualificationState: "NOT_QUALIFIED", visibility: "PUBLIC_CORE", supportedTargetTypes: ["repository", "web_application", "static_library"], origin },
    { serviceId: "AGENTSEC", name: "Agent Security", version: "0.1.0", qualificationState: "NOT_QUALIFIED", visibility: "PUBLIC_CORE", supportedTargetTypes: ["agent_system", "agentic_web_saas"], origin },
    { serviceId: "VULNINTEL", name: "Vulnerability Intelligence", version: "0.1.0", qualificationState: "NOT_QUALIFIED", visibility: "PUBLIC_CORE", supportedTargetTypes: ["repository", "web_application", "static_library"], origin },
    { serviceId: "SUPPLYCHAIN", name: "Supply-Chain Security", version: "0.1.0", qualificationState: "NOT_QUALIFIED", visibility: "PUBLIC_CORE", supportedTargetTypes: ["repository", "web_application", "static_library"], origin },
  ],
  approvals: [
    {
      approvalId: "APR-015-004",
      engagementId: "ENG-2026-015",
      requestedBy: "agent.security-review-v1",
      requestRef: "CAP-ADVISORY-015-004",
      targetId: "TGT-VPP-SNAPSHOT",
      capabilityId: "CAP-ADVISORY-READ",
      action: "inspect",
      risk: "medium",
      decision: "pending",
      requestFingerprint: "sha256: 4aa1…92d0",
      rationale: "Exact binding required before advisory artifact access.",
      origin,
    },
  ],
  clients: [
    { clientId: "CLI-VPP", name: "Synthetic agent client", targetCount: 1, engagementCount: 1, status: "closed qualification", origin },
    { clientId: "CLI-AGENT", name: "Agent Systems Lab", targetCount: 1, engagementCount: 1, status: "active qualification", origin },
  ],
  targets: [
    { targetId: "TGT-VPP-SNAPSHOT", clientId: "CLI-VPP", name: "Synthetic agent client snapshot", kind: "repository", snapshot: "immutable snapshot", snapshotDigest: "sha256: f364…43b1", liveCheckout: "separate", origin },
    { targetId: "TGT-AGENT-SNAPSHOT", clientId: "CLI-AGENT", name: "agent repository snapshot", kind: "repository", snapshot: "qualification-only", snapshotDigest: "sha256: synthetic", liveCheckout: "unknown", origin },
  ],
  reports: [
    {
      engagementId: "ENG-2026-015",
      title: "ENG-2026-015 · Posture assessment",
      verdict: "PASS_WITH_LIMITATIONS",
      scope: "Synthetic repository qualification only.",
      generatedAt: "2026-08-15T18:40:00Z",
      reportSha256: "sha256: 11a7…63dd",
      limitationCount: 1,
      findingIds: ["FND-PREV-015"],
      evidenceIds: ["E-1181"],
      noSecretsAssertion: "asserted",
      origin,
    },
  ],
  detectionSignals: [
    {
      id: "SIG-PREV-022-001",
      signalId: "SIG-PREV-022-001",
      caseId: "ENG-2026-022",
      ruleId: "secscan.endpoint.privilege-escalation",
      ruleVersion: 1,
      severity: "High",
      confidence: "High",
      state: "NEW",
      eventIds: ["EVT-PREV-ENDPOINT-001", "EVT-PREV-ENDPOINT-002"],
      evidenceRefs: ["EV-PREV-022-001"],
      scope: { tenantId: "tenant-preview", caseId: "ENG-2026-022" },
      source: "synthetic detection qualification",
      origin,
    },
  ],
  hunts: [
    {
      id: "HUNT-PREV-022-001",
      huntId: "HUNT-PREV-022-001",
      hypothesisId: "HYP-PREV-022-001",
      caseId: "ENG-2026-022",
      disposition: "VERIFIED",
      state: "VERIFIED",
      evidenceRefs: ["EV-PREV-022-001", "EV-PREV-022-002"],
      scope: { tenantId: "tenant-preview", caseId: "ENG-2026-022" },
      source: "synthetic threat-hunt qualification",
      origin,
    },
  ],
  incidents: [
    {
      id: "INC-PREV-022-001",
      incidentId: "INC-PREV-022-001",
      caseId: "ENG-2026-022",
      state: "CONFIRMED",
      severity: "High",
      confidence: "High",
      signalIds: ["SIG-PREV-022-001"],
      evidenceRefs: ["EV-PREV-022-001", "EV-PREV-022-002"],
      scope: { tenantId: "tenant-preview", caseId: "ENG-2026-022" },
      provenance: { source: "synthetic incident adjudication", sourceType: "qualification", observedAt: "2026-08-16T10:20:00Z", evidenceRefs: ["EV-PREV-022-001", "EV-PREV-022-002"], status: "CONFIRMED" },
      origin,
    },
  ],
  responseProposals: [
    {
      id: "RSP-PREV-022-001",
      proposalId: "RSP-PREV-022-001",
      incidentId: "INC-PREV-022-001",
      caseId: "ENG-2026-022",
      targetId: "TGT-AGENT-SNAPSHOT",
      action: "isolate_target",
      opaDecision: "APPROVAL_REQUIRED",
      humanApprovalState: "APPROVAL_REQUIRED",
      state: "APPROVAL_REQUIRED",
      evidenceRefs: ["EV-PREV-022-001", "EV-PREV-022-002"],
      scope: { tenantId: "tenant-preview", caseId: "ENG-2026-022" },
      source: "synthetic response proposal qualification",
      origin,
    },
  ],
  audit: [
    { auditEventId: "AUD-015-17", engagementId: "ENG-2026-015", principalId: "operator-local", kind: "policy_decision", summary: "CAP-ADVISORY-READ evaluated within inspection-only scope.", occurredAt: "2026-08-15T17:43:00Z", relatedIds: ["AR-015-COORD-01"], origin },
  ],
  graphNodes: [
    { id: "node-snapshot", kind: "snapshot", label: "immutable repository snapshot", state: "VERIFIED", relatedIds: ["FND-PREV-015"], scope: { tenantId: "tenant-preview", caseId: "ENG-2026-015" }, provenance: { source: "snapshot registry", sourceType: "preview", observedAt: "2026-08-15T18:40:00Z", evidenceRefs: ["E-1181"], status: "VERIFIED" } },
    { id: "node-finding", kind: "finding", label: "Advisory data is unavailable for the review capability.", state: "INCONCLUSIVE", relatedIds: ["FND-PREV-015"], scope: { tenantId: "tenant-preview", caseId: "ENG-2026-015" }, provenance: { source: "patrol projection", sourceType: "preview", observedAt: "2026-08-15T18:40:00Z", evidenceRefs: ["E-1181"], status: "INCONCLUSIVE" } },
    { id: "node-capability", kind: "capability", label: "CAP-ADVISORY-READ", state: "APPROVAL_REQUIRED", relatedIds: ["FND-PREV-015"], scope: { tenantId: "tenant-preview", caseId: "ENG-2026-015" }, provenance: { source: "capability registry", sourceType: "preview", observedAt: "2026-08-15T17:43:00Z", evidenceRefs: [], status: "APPROVAL_REQUIRED" } },
  ],
  graphEdges: [
    { id: "edge-snapshot-finding", sourceId: "node-snapshot", targetId: "node-finding", relation: "supports", state: "VERIFIED", relatedIds: ["FND-PREV-015"], scope: { tenantId: "tenant-preview", caseId: "ENG-2026-015" }, provenance: { source: "evidence linkage", sourceType: "preview", observedAt: "2026-08-15T18:40:00Z", evidenceRefs: ["E-1181"], status: "VERIFIED" } },
    { id: "edge-finding-capability", sourceId: "node-finding", targetId: "node-capability", relation: "depends on", state: "INCONCLUSIVE", relatedIds: ["FND-PREV-015"], scope: { tenantId: "tenant-preview", caseId: "ENG-2026-015" }, provenance: { source: "patrol projection", sourceType: "preview", observedAt: "2026-08-15T18:40:00Z", evidenceRefs: ["E-1181"], status: "INCONCLUSIVE" } },
  ],
};
